# Generated by Django 5.0.4 on 2024-04-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('cover_image', models.ImageField(upload_to='covers/')),
                ('body', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('topics', models.ManyToManyField(related_name='posts', to='blog.topic')),
            ],
        ),
    ]
